name: Simple-EFI-Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Compiler
        run: sudo apt-get install -y clang lld llvm

      - name: Compile EFI
        run: |
          mkdir -p build
          # On compile tous les .c présents dans src/
          clang -target x86_64-unknown-windows -ffreestanding -fshort-wchar -mno-red-zone -I./include -c src/*.c
          lld-link -entry:efi_main -subsystem:efi_application -out:build/BOOTX64.EFI *.o

      - name: Upload BOOTX64.EFI
        uses: actions/upload-artifact@v4
        with:
          name: RadicalBoot-Binary
          path: build/BOOTX64.EFI
